#include "xmlfilehandler.h"

#include <QString>
#include <QFile>
#include <QDebug>
#include <QDir>
#include <QDomDocument>
#include "helpers.h"
#include "projectmanager.h"

XmlFileHandler::XmlFileHandler(QString path, QString name)
{
	QDir dir(path);
	if ( dir.exists() ) {
		filePath = path+"/"+name+".xml";
	} else {
		qDebug() << "ERROR from "<<__func__<<" Path does not exist!";
	}
}


void XmlFileHandler::createFile()
{

	QFile file(filePath);

	if ( !file.exists() ) {
		if ( !file.open(QIODevice::ReadWrite) ) {
			qDebug() << "ERROR from "<<__func__<<" Could not create file";
		}
	} else {
		qDebug() << "ERROR from "<<__func__<<" File does already exist!";
	}

	file.close();
}

QString XmlFileHandler::openFile()
{
	QFile file(filePath);
	QString content;
	if ( file.exists() ) {
		if ( !file.open(QIODevice::ReadWrite) ) {
			qDebug() << "ERROR from "<<__func__<<" Could not open file";
		}
	} else {
		qDebug() << "ERROR from "<<__func__<<" File does not exist";
	}

	content = QString::fromUtf8(file.readAll());
	file.close();
	return content;
}

void XmlFileHandler::XMLautoGenerate()
{
	ProjectManager *projectmanager = ProjectManager::getInstance();
	ProjectManager::projectSettings set = projectmanager->getNewProjectSettings();

	QFile templateFile(":/autogeneratedXML.xml");
	QDomDocument doc;
	doc = helpers::parseXMLFile(&templateFile);

	QDomElement root = doc.firstChildElement("ns0:RootFileSystem");
//	qDebug() << root.tagName();

	QDomNode projectNode;
	QDomNode rootChildNode = root.firstChild();
	while (!rootChildNode.isNull()) {
		QDomElement childElement = rootChildNode.toElement();
		qDebug() << childElement.tagName();
		if ( childElement.tagName().compare("project") == 0 ) {
			projectNode = rootChildNode;
		}
		rootChildNode = rootChildNode.nextSibling();
	}

	QDomNode mirrorNode;
	QDomNode projectChildNode = projectNode.firstChild();
	while( !projectChildNode.isNull() ) {
		QDomElement projectChildElement = projectChildNode.toElement();
//		qDebug() << projectChildElement.tagName();
		if (projectChildElement.tagName().compare("name")) {
			projectChildNode.appendChild(doc.createTextNode(set.name));
		} else if(projectChildElement.tagName().compare("version")){
			projectChildNode.appendChild(doc.createTextNode(set.version));
		} else if(projectChildElement.tagName().compare("description")){
			projectChildNode.appendChild(doc.createTextNode(set.description));
		} else if(projectChildElement.tagName().compare("buildtype")){
			projectChildNode.appendChild(doc.createTextNode(set.buildtype));
		} else if(projectChildElement.tagName().compare("suite")){
			projectChildNode.appendChild(doc.createTextNode(set.suite));
		} else if(projectChildElement.tagName().compare("mirror")){
			mirrorNode = projectChildNode;
		}

		projectChildNode = projectChildNode.nextSibling();
	}

	QDomNode mirrorChildNode = mirrorNode.firstChild();
	while ( !mirrorChildNode.isNull() ) {
		QDomElement mirrorChildElement = mirrorChildNode.toElement();
//		qDebug() << mirrorChildElement.tagName();
		if(mirrorChildElement.tagName().compare("primary_host")){
			mirrorChildNode.appendChild(doc.createTextNode(set.host));
		} else if(mirrorChildElement.tagName().compare("primary_path")){
			mirrorChildNode.appendChild(doc.createTextNode(set.path));
		} else if(mirrorChildElement.tagName().compare("primary_proto")){
			mirrorChildNode.appendChild(doc.createTextNode(set.proto));
		}

		mirrorChildNode = mirrorChildNode.nextSibling();
	}



	QByteArray xml = doc.toByteArray(4);

	QFile file(filePath);
	helpers::saveXMLChanges(&file, xml);
}


void XmlFileHandler::saveFile()
{

}


void XmlFileHandler::closeFile()
{

}
